server:
  max-http-header-size: 20480
  port: 9002
  servlet:
    context-path: /unlimited
  tomcat:
    basedir: /data/tmp
eureka:
  client:
    serviceUrl:
      defaultZone: http://114.215.80.109:8761/eureka/
spring:
  application:
    name: yog-unlimited
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://114.215.80.109:3306/unlimited?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false
    username: root
    password: YOGjun23
    druid:
      initial-size: 2
      max-active: 30
      min-idle: 2
      max-wait: 1234
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 5
      validation-query: select 1
      validation-query-timeout: 1
      test-on-borrow: true
      test-on-return: true
      test-while-idle: true
      time-between-eviction-runs-millis: 10000
      min-evictable-idle-time-millis: 30001
      async-close-connection-enable: true
      filter:
        stat:
          db-type: mysql
          log-slow-sql: true
          slow-sql-millis: 2000
    session:
      store-type: redis
    servlet:
      multipart:
        max-file-size: 10Mb
        max-request-size: 100Mb
  redis:
    cluster:
      nodes:
        - 127.0.0.1:6379
        - 127.0.0.1:6379
        - 127.0.0.1:6379
      so-timeout: 1500
      connection-timeout: 800
      max-attempts: 3

  mybatis:
    mapper-locations: classpath:mapper/**/*.xml
    type-aliases-package: cn.yog.unlimited.entity
  pagehelper:
    reasonable: false
    helper-dialect: mysql
    support-methods-arguments: true
    params: count=countSql
  mapper:
    mappers:
      - tk.mybatis.mapper.common.Mapper
    notEmpty: true
  feign:
    httpclient:
      enabled: true
      connection-timeout: 10000
  ribbon:
    OkToRetryOnAllOperations: false
    ReadTimeout: 20000
    ConnectTimeout: 2000
    MaxAutoRetries: 0
    MaxAutoRetriesNextServer: 1

management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    root: info
    cn.yog.unlimited: debug

swagger:
  enable: true
  base-package: "cn.yog.unlimited.controller"
  title: Yog Web Api Document
  description: YOGJUN API在线文档
